# Generated by Django 4.1.4 on 2022-12-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=30)),
                ('E_mail', models.CharField(max_length=30)),
                ('Mobile_number', models.BigIntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('password', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=30)),
                ('seller_address', models.CharField(max_length=30)),
                ('seller_phone', models.CharField(max_length=30)),
                ('seller_email', models.CharField(max_length=40)),
                ('seller_companyname', models.CharField(max_length=100)),
                ('seller_accholder', models.CharField(default='', max_length=30)),
                ('seller_ifsc', models.CharField(max_length=30)),
                ('seller_branch', models.CharField(max_length=30)),
                ('seller_accno', models.CharField(max_length=30)),
                ('seller_password', models.CharField(max_length=30)),
                ('seller_pic', models.ImageField(upload_to='seller/')),
                ('seller_user', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
