# Generated by Django 4.1.3 on 2022-12-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_seller_seller_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_accno',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_branch',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_ifsc',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_password',
            field=models.CharField(max_length=30),
        ),
    ]
